#!/bin/bash
#    Copyright (C) 2017  Jonathan Jason Dennis [Meticulus]
#					theonejohnnyd@gmail.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

source common.cfg

THISDIR=$PWD
REPO=$(getRepo)
TOP=$(getTop)
PATCHDIR=$(getDevice)/patches
ROM=$(getRom)

clearrepo

checkerror $? "Could not clear repo!"

cd $TOP

cd $PATCHDIR

checkerror $? "$PWD/$PATCHDIR not found!"

patcher rom=$ROM repo=$REPO

checkerror $? "patcher failed!"

cd $THISDIR

git status
