#!/bin/bash
#    Copyright (C) 2017  Jonathan Jason Dennis [Meticulus]
#					theonejohnnyd@gmail.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PATCH=${1}

if [[ "$PATCH" == "" ]]; then
	echo "Patch no specified!"
	exit 9
fi

if [[ "$PATCH" == *".patch" ]]; then
	echo 1
elif [[ "$PATCH" == *".apply" ]]; then
	echo 2
elif [[ "$PATCH" == *".disabled" ]]; then
	echo 3
elif [[ "$PATCH" == *".applydisabled" ]]; then
	echo 4
else
	echo "Not a patch!!!"
	exit 9
fi
